### PR TITLE
add support for requester_pays to google_storage_bucket

### PR DESCRIPTION
**Pull request by lawrenae**
This is a fix for issue #2332. As you can see, I've built this on top of the 2.0.0 branch, but was unsure if it's more appropriate to use master or something else -- I'm happy to move it and feedback on the changes most welcome, so please let me know.

Thanks

### CODE REVIEW

**Comment by lawrenae** [comment]
Travis seems to have failed for a gofmt on a file I didnt touch and `make website-test` has broken links. is this something I can/should fix?

**Comment by lawrenae** [comment]
I'll add the documentation shortly. Thanks!

**Comment by ndmckinley** [comment]
GitHub seems to have been wildly confused about that first commit - my theory is that your commit had the `master` base branch at first and that confused it.  Your new commit seems right.  :)

**Comment by lawrenae** [comment]
@ndmckinley Thanks for approving -- is there a rough idea of when 2.0.0 will be released (or what else needs to happen to complete it) ?

**Comment by danawillow** [comment]
@ndmckinley have you moved this into MM?

**Comment by ndmckinley** [comment]
I haven't - I'll make sure to do that, and that it gets into the 1.20 release branch.

**Comment by rileykarson** [comment]
Looks like this was resolved with https://github.com/terraform-providers/terraform-provider-google/pull/2580?

It didn't make it in to `1.20.0` - this should release as part of `2.0.0`.

**Pull request closed without merging**
