### PR TITLE
The tags argument specifics network tags to attach to the instance

### PR DESCRIPTION
**Pull request by dmyerscough**
The `tags` argument specifies `network tags` that are to be attached to the instance.

### CODE REVIEW

**Comment by ndmckinley** [comment]
Hmm, thanks for the proposal, but I'm not sure that that's clearer - how would you distinguish a network tag from any other kind of tag?

**Comment by dmyerscough** [comment]
When using the AWS module, they use `tags` for tagging instances.

```
tags          = {
    Name        = "Application Server"
    Environment = "production"
  }
```

However, in GCP the equivalent is metadata. I thought it would've been a little more clear since GCP "tags" in this scenario refer to network tags.

**Comment by ndmckinley** [comment]
Got it - I agree, the docs do use the terms "network tags" and "tags" interchangeably, and that does sound clearer to an AWS user.  Thanks!

The docs I'm referring to are https://cloud.google.com/vpc/docs/add-remove-network-tags.  :)

Would you mind proposing this change to [this file](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/website/docs/r/compute_instance.html.markdown) instead?  This code is automatically generated from that code, so a change only here would be clobbered.

**Comment by dmyerscough** [comment]
Thank you @ndarilek, PR opened: https://github.com/GoogleCloudPlatform/magic-modules/pull/3557

**Pull request closed without merging**
