### PR TITLE
Update vendored deps

### PR DESCRIPTION
**Pull request by SirGitsalot**
I'm working on Stackdriver monitoring in another branch, which required updating `google.golang.org/genproto`, which required updating `google.golang.org/grpc`, which required updating `github.com/golang/protobuf`, and so on. This PR updates all of the Google-provided deps to their latest versions. In addition, there is:

- A change in config.go to reflect an updated type name
- Five files changed by `make fmt`

Tested with `make build`, `make test`, and `make testacc`.

### CODE REVIEW

**Comment by SirGitsalot** [comment]
Updated to remove some stale deps that made `make vendor-status` barf.

**Comment by danawillow** [comment]
Oh dang that's a lot of updates! It also looks like travis still failed, mind checking that out? Once that's fixed, I'll kick off a full test suite run on this since it's a change that has the capability of breaking a lot of things.

**Comment by rileykarson** [comment]
Looks like the `go fmt` issues are because of a change between Go 1.10 and Go 1.11. Try downgrading your Go version to fix those!

Personally, I used (with homebrew on MacOS)

```
brew install go@1.10
```

Then set these environment variables in my .bashrc:
```
export GOROOT=~/homebrew/opt/go@1.10/libexec/bin
export PATH="~/homebrew/opt/go@1.10/bin:$PATH"
```

**Comment by SirGitsalot** [comment]
Travis build fixed.

**Comment by ndmckinley** [comment]
I'm running the tests on this branch on CI.  :)

**Comment by ndmckinley** [comment]
Oh, I never came back around to this - LGTM.  Some server errors and flakes on the test run but nothing serious.

**Comment by SirGitsalot** [comment]
@danawillow @ndmckinley I don't have write access, so merge please :-)

**Pull request merged**
