### PR TITLE
Don't attempt to delete default users on replica

### LINKED ISSUE #347: New Google Cloud SQL failover replica resource shouldn't try to delete root user
### Terraform Version
0.10.2

### Affected Resource(s)
Please list the resources as a list, for example:
- google_sql_database_instance

### Terraform Configuration Files
```hcl
// GCP Cloud SQL Primary DB in Primary Region, Primary Zone
resource "google_sql_database_instance" "db-primary" {
  provider           = "google.gcp-${var.region_primary}"
  region             = "${var.sqlregion_primary}"
  database_version   = "MYSQL_5_7"

  settings {
    tier             = "db-n1-standard-1"

    database_flags {
        name         = "character_set_server"
        value        = "utf8mb4"
    }

    backup_configuration {
        binary_log_enabled = "true"
        enabled            = "true"
        start_time         = "18:00"
    }

    ip_configuration {
        require_ssl        = "true"
    }

    location_preference {
        zone               = "${var.region_primary_zone_primary}"
    }
  }
}

// GCP Cloud SQL Secondary DB in Primary Region, Secondary Zone
resource "google_sql_database_instance" "db-failover" {
  provider           = "google.gcp-${var.region_primary}"
  region             = "${var.sqlregion_primary}"
  database_version   = "MYSQL_5_7"
  master_instance_name = "${google_sql_database_instance.db-primary.name}"

  replica_configuration {
    connect_retry_interval = "30"
    failover_target        = "true"
  }

  settings {
    tier             = "db-n1-standard-1"

    database_flags {
        name         = "character_set_server"
        value        = "utf8mb4"
    }

    ip_configuration {
        require_ssl        = "true"
    }

    location_preference {
        zone               = "${var.region_primary_zone_secondary}"
    }
  }
}
```

### Expected Behavior
The resource should be created without issue.

### Actual Behavior
The resource is created, but with error output in red:
```
Error applying plan:

1 error(s) occurred:

* google_sql_database_instance.db-failover: 1 error(s) occurred:

* google_sql_database_instance.db-failover: Error, failed to delete default 'root'@'*' user, but the database was created successfully: googleapi: Error 400: The requested operation is not valid for a read-replica instance., errorReadReplicaInvalidOperation

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
1. Create a database instance with resource type google_sql_database_instance
2. Create a failover replica instance with almost all of the same settings, but remove the backup_configuration section and add the replica_configuration section.
3. Watch error output.

### Important Factoids
On page https://www.terraform.io/docs/providers/google/r/sql_database_instance.html, at the top in yellow it specifically says this resource type will delete the default 'root' user that Cloud SQL creates for you, and you need to define your own root user (which I do). However, this isn't a valid action for the failover replica.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-google/issues/100

### PR DESCRIPTION
**Pull request by selmanj**
Fixes #347

### CODE REVIEW

**Comment by selmanj** [comment]
It did not. I was going to write a test but thought that the additional test might not be worth it since it's a failure situation that users shouldn't run into anymore (and each test has a cost, after all; in this case it's in the minutes).

However I think there's something to be said about someone who wants their own `root@'%'` user that's managed within terraform; if they end up adding replicas later, they'll end up hitting this same path. In that case it probably makes sense to have this failure scenario covered.

**Comment by selmanj** [comment]
I added a test ensuring we don't delete a root user found on the replica. It currently fails on master and passes on this branch. 

The test itself is not great to read; would love input on how to make this more readable using the `resource.TestCase`/`resource.TestStep` structs.

**Comment by ryan-mf** [comment]
This was merged into master 12 days ago, but terraform-provider-google hasn't had a release since 1.3 on 8/17/2017:
https://github.com/terraform-providers/terraform-provider-google/releases

Now that Terraform is modular, we have to wait for the module to get its own release. Any idea when there will be a new release for terraform-provider-google?

**Comment by selmanj** [comment]
I agree @ryan-mf; we're focusing on that now (we are working on making our underlying test suite happy).  Should be very soon...

**Pull request merged**
