### PR TITLE
Update AppEngine locations

### PR DESCRIPTION
**Pull request by letic**
I needed to use Zurich (europe-west6) for a project and terraform wouldn't accept it.

So here is a simple patch to update AppEngine locations with latest from Google official documentation located at : https://cloud.google.com/appengine/docs/locations

Cheers
LeTic

### CODE REVIEW

**Comment by letic** [comment]
Error details during Terraform plan : 
`Error: google_app_engine_application.xxxxx-dev: expected location_id to be one of [northamerica-northeast1 us-central us-west2 us-east1 us-east4 southamerica-east1 europe-west europe-west2 europe-west3 asia-northeast1 asia-south1 australia-southeast1], got europe-west6`

**Comment by danawillow** [comment]
Thanks @letic! I'm fairly sick of having to keep this list up-to-date, and it doesn't quite feel like it's worth having the validation for something that we keep having to change like this. Mind just ripping it out entirely?

**Comment by letic** [comment]
Hey @danawillow sorry about the delay. 

Here's a version without the region validation function. Simple enough should be easy to merge.

Take care
LeTic

**Comment by letic** [comment]
No worries. Thanks for the good work :)

**Pull request merged**
