### PR TITLE
Update region in sql db docs

### PR DESCRIPTION
**Pull request by danawillow**
Since the available regions might change over time, link to the GCP documentation instead of trying to provide our own list.

@danielcompton would you say this is enough for #449?

### CODE REVIEW

**Comment by danielcompton** [comment]
It looks like for second generation instances all of the names line up with [actual regions](https://cloud.google.com/compute/images/zones_diagram.svg). The only oddball in the SQL list is `us-central` for first-gen SQL instances. For second-gen I don't think there is any distinction to make. I think it would be less confusing to say:

> region - (Required) The region the instance will sit in. Note, first-generation Cloud SQL instance regions do not line up with the Google Compute Engine (GCE) regions - choose from one of the options listed here.

**Comment by danawillow** [comment]
True, but not all GCE regions can be used for Cloud SQL (asia-southeast1 is missing)

**Comment by danielcompton** [comment]
How about:

> region - (Required) The region the instance will sit in. Note, first-generation Cloud SQL instance regions do not line up with the Google Compute Engine (GCE) regions, and Cloud SQL is not available in all regions - choose from one of the options listed here.

Otherwise what you've got is fine too.

**Comment by danawillow** [comment]
I like it, thanks!

**Pull request merged**
