### PR TITLE
Make email, project computed for GCE default service account

### LINKED ISSUE #1686: Race condition with projects and outputs
Hi There, 
I'm looking for some advice to make this collection of resources work.  We're basically trying to:

- Setup a new project
- Enable compute API
- Get the default service account email address

```
resource "google_project" "project" {
...
}

resource "google_project_services" "enabled-apis" {
  project = "${google_project.project.project_id}"
  services = ["compute.googleapis.com"]
}

data "google_compute_default_service_account" "default" {
  project = "${google_project.project.project_id}"
}

output "default_account" {
  value = "${data.google_compute_default_service_account.default.email}"
}
```

However it results in this during the plan:

```
* module.project-infrastructure-sandbox.output.default_account: Resource 'data.google_compute_default_service_account.default' does not have attribute 'email' for variable 'data.google_compute_default_service_account.default.email'
```

So it looks like the output variable is trying to read `.email` from the data resource during the plan.

Any ideas?

### PR DESCRIPTION
**Pull request by emilymye**
Fixes #1686

### CODE REVIEW

**Comment by emilymye** [comment]
TF_ACC=1 go test ./google -v --run="TestAccDataSourceGoogleComputeDefaultServiceAccount_basic" -timeout 120m
=== RUN   TestAccDataSourceGoogleComputeDefaultServiceAccount_basic
=== PAUSE TestAccDataSourceGoogleComputeDefaultServiceAccount_basic
=== CONT  TestAccDataSourceGoogleComputeDefaultServiceAccount_basic
--- PASS: TestAccDataSourceGoogleComputeDefaultServiceAccount_basic (1.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	1.548s

**Comment by emilymye** [comment]
Should I still just go ahead and merge it in if it's a breaking change?

**Comment by danawillow** [comment]
I'm very confident that this is not a breaking change.

**Comment by paddycarver** [comment]
Just chiming in late that now that I understand what's going on here, I also am 👍 on this being merged now and not considering it a breaking change.

**Pull request merged**
