### PR TITLE
Copy network_interface attributes back to state on resourceComputeInstanceRead(). (Fixes #519)

### LINKED ISSUE #519: Compute instance IP addresses are not detected
### Terraform Version
```
root@400e33249198:/devops/bastion# terraform -v
Terraform v0.10.7

root@400e33249198:/devops/bastion# gcloud -v
Google Cloud SDK 173.0.0
alpha 2017.09.25
beta 2017.09.25
bq 2.0.26
core 2017.09.25
gsutil 4.27
```

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
provider "google" {
    project     = "truveon-prototype"
    region      = "us-west1"
}

terraform {
    backend "gcs" {
        bucket  = "truveon-state-prototype"
        path    = "bastion.tfstate"
        project = "truveon-prototype"
    }
}

variable "savanniCredentials" {
    default = {
        user = "savanni",
        keyFile = "../luminescent-dreams.pub"
    }
}

resource "google_dns_managed_zone" "truveon" {
    name        = "truveon"
    dns_name    = "truveon.com."
}

resource "google_dns_record_set" "bastion" {
    name            = "staging.${google_dns_managed_zone.truveon.dns_name}"
    type            = "A"
    ttl             = 300
    managed_zone    = "${google_dns_managed_zone.truveon.name}"
    rrdatas         = ["${google_compute_instance.bastion.network_interface.0.address}"]
}

resource "google_compute_instance" "bastion" {
    name            = "bastion"
    machine_type    = "f1-micro"
    zone            = "us-west1-b"

    tags            = ["bastion"]

    boot_disk {
        initialize_params {
            image = "debian-cloud/debian-8"
        }
    }

    network_interface {
        network = "default"
        access_config { }
    }

    metadata {
        sshKeys = "${var.savanniCredentials["user"]}:${file(var.savanniCredentials["keyFile"])}"
    }
}
```

### Debug Output

https://gist.github.com/savannidgerinel/6e4ec396a78900a4d242d15588fca00b

### Expected Behavior

I expected this command to complete having created one DNS zone, one compute instance, and a DNS entry for that compute instance.

### Actual Behavior

The zone and compute instance were both created. The DNS entry was not created and the error indicated that the referenced IP address was not set:

```
* google_dns_record_set.bastion: Error creating DNS RecordSet: googleapi: Error 400: Invalid value for 'entity.change.additions[0].rrdata[0]': '', invalid
```

The state also shows a lot of empty `network_interface` fields.

```
root@400e33249198:/devops/bastion# GOOGLE_APPLICATION_CREDENTIALS=... terraform show | grep network_interface
  network_interface.# = 1
  network_interface.0.access_config.# = 1
  network_interface.0.access_config.0.assigned_nat_ip = 
  network_interface.0.access_config.0.nat_ip = 
  network_interface.0.address = 
  network_interface.0.alias_ip_range.# = 0
  network_interface.0.name = 
  network_interface.0.network = default
  network_interface.0.subnetwork = 
  network_interface.0.subnetwork_project = 
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

This was largely lifted from  the terraform GCS documentation except for the server and DNS names.

### PR DESCRIPTION
**Pull request by PeterMilley**
Fixes #519.

Added an acceptance test for coverage.

### CODE REVIEW

**Comment by PeterMilley** [comment]
@paddycarver, gentle bump?

**Comment by kszarek** [comment]
Is there any news on this one?

**Comment by rosbo** [comment]
@paddycarver The `d.Set("network_interface", networkInterfaces)` line was deleted by mistake when the deprecated resources were deleted prior to the 1.0.0 release: https://github.com/terraform-providers/terraform-provider-google/commit/f2f276ea0b8a98fa782a9321a9d4b55122e27fe5#diff-6ebc1a840e42235a51a46d537f17ddaa

**Comment by rosbo** [comment]
```sh
=== RUN   TestAccComputeInstance_GenerateIP
--- PASS: TestAccComputeInstance_GenerateIP (181.66s)
```

Thank you Peter for the fix! It will be included in the next release of the google provider.

**Comment by anas-aso** [comment]
@rosbo thanks for merging this. any idea when will be the next release ? this is a kind of blocker to us.

**Comment by christopher-demarco** [comment]
Yes please—what is the ETA for release? 
Critical blocker for high-profile public demo on 30 Oct :-(

**Comment by genevievelesperance** [comment]
@christopher-demarco You can pin the google provider version in your template to `version = "0.1.3"` until they merge the PR for the fix.

**Comment by christopher-demarco** [comment]
Where is the "thank-you-internet-beer-for-you" emoji?

**Comment by rosbo** [comment]
We definitely want to get a release out with this fix ASAP. I can't share an ETA until I have spoken with @paddycarver. Stay tuned.

**Comment by paddycarver** [comment]
Apologies all, busy day. Thanks @rosbo for the merge. We've got one last bug we're trying to fix, and are anticipating a release rather soon. I can't promise dates, but we're aware of the urgency of getting a bugfix release out for this. Sorry for the issues.

**Comment by christopher-demarco** [comment]
Thanks folks, it's super-appreciated. FLOSS devs are _the best_!

**Comment by pydevops** [comment]
Verified the network_interface.0.address works now after the 1.1.0 released

**Pull request merged**
