### PR TITLE
Added Storage Transfer package

### PR DESCRIPTION
**Pull request by akramhussein**
FAO @rileykarson 

Part of multi-PR for adding support for Google Storage Transfer Service.

See https://github.com/terraform-providers/terraform-provider-google/pull/2181

### CODE REVIEW

**Comment by rileykarson** [comment]
My apologies for the extra round trip here! I missed this the first time. Can you make the changes to `config.go` against this file? https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/utils/config.go.erb

Feel free to submit separately or as a part of https://github.com/GoogleCloudPlatform/magic-modules/pull/1068

**Comment by akramhussein** [comment]
I've added it to GoogleCloudPlatform/magic-modules#1068

Do you need me to remove it from here?

**Comment by rileykarson** [comment]
If you don't mind! Magic Modules will attempt to remove it in every PR until the MM pr is merged. Sorry for the weirdness around vendoring new packages with MM, it's a little silly how we end up needing to break changes up.

**Comment by akramhussein** [comment]
No worries - done now. Will do in `beta` too.

**Comment by akramhussein** [comment]
Done in `beta`. Is all that remains is me to sign the `CLA`?

**Comment by rileykarson** [comment]
If you don't mind! If you're unable to, the `third_party/` directory doesn't require it, the bot just doesn't know that. I'll merge these vendor PRs as Travis finishes & start running the Magician to generate downstreams on  https://github.com/GoogleCloudPlatform/magic-modules/pull/1068.

**Pull request merged**
