### PR TITLE
Set the correct default for UseLegacySQL

### PR DESCRIPTION
**Pull request by jimmy-btn**

### CODE REVIEW

**Comment by paddycarver** [comment]
Hey there @jimmy-btn, I'm looking at this PR (sorry for the delay!) and it seems... a bit odd. There seem to be a lot of commits to change `Default` to `true`. Could we squash the commits down? And can you provide any insight on why the `Default` should be `true`? Thanks!

**Comment by paddycarver** [comment]
Hey @jimmy-btn, without more info on why these changes are being made, I'm going to go ahead and close this PR. But I'm certainly happy to reopen and move forward with it, just reply here and let us know. Thanks!

**Comment by jimmy-btn** [comment]
Hi Paddy - my apologies, I missed your original comment!

The commit history mess is my bad; let me clean that up and get this PR
into a better shape.

This change is motivated by an unintentional bug I introduced when adding
View support to BigQuery Tables.

**Comment by paddycarver** [comment]
No problem at all. Let's reopen this then, and we can move it forward. 👍

**Comment by jimmy-btn** [comment]
Hey Paddy - I somehow got my workspace into a terrible state. Rather than
drag that mess into the repo, I created a clean PR here:
https://github.com/terraform-providers/terraform-provider-google/pull/724

Let's close this one out and follow up there.

**Pull request closed without merging**
