### PR TITLE
Add machine_type configuration to google_dataflow_job

### PR DESCRIPTION
**Pull request by propan**
Would be quite convenient to have that feature.

### CODE REVIEW

**Comment by BenFradet** [comment]
what's missing to get this merged?

**Comment by emilymye** [comment]
Sorry for the delay - we've had some large changes happen recently and now all of our code is being generated through Magic Modules ([repo](https://github.com/GoogleCloudPlatform/magic-modules)) in order to allow for autogeneration of some resources and versioned providers.

However, it means we've lost track of some PRs, especially those that need to be transferred over to the new code location in Magic Modules (for example, the  [resource_dataflow_job.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_dataflow_job.go) file). 

We haven't had the time yet to get to these reviews or to transfer them over ourselves. If someone from the community needs it sooner than we get to it, please feel free to try opening a PR against MM and we'll help walk you through the new process for contributing. Thank you!

**Comment by danawillow** [comment]
Hi @propan, if you're still interested in this PR, I believe the outstanding need is to set the field in the read function (and merge/rebase on master). If I don't hear back within the week, I'll go ahead and close this so someone else can get to it.

**Comment by tysen** [comment]
Merged here: https://github.com/GoogleCloudPlatform/magic-modules/pull/1862

**Pull request closed without merging**
