### PR TITLE
Fix an issue where the HTTP response from the SQL service was inconsistent when doing a GET after DELETE on a sql_database

### PR DESCRIPTION
**Pull request by spew**
Scenario is as follows

1. Create sql_instance
2. Create sql_database referencing sql_instance
3. Delete sql_database
4. Delete sql_instance
5. Perform get request on sql_database

Expected behavior: Normal "NotFound" behavior that everything relies on (like Delete, etc)

Actual behavior: Error

### CODE REVIEW

**Comment by spew** [comment]
It works -- gErr is a pointer value so while this statement holds true:

  `&gErr != &err`

this IS also true:

  `gErr == err`


i.e. gErr and err are both pointer values (of different types) and both contain the same pointer value (aka memory address).

**Comment by rileykarson** [comment]
Mind checking if the changes in https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3396-old..auto-pr-3396 work for your test?

**Comment by spew** [comment]
Yes, I will try with that today.

**Comment by rileykarson** [comment]
Thanks! I'm gonna hold merging the upstream on that, since we're choosing next week's release commit at EOD I'd like to make sure it works for you.

**Comment by spew** [comment]
Test results without either change:

```
    TestCRUD/basic-sqldatabase: client_integration_test.go:93: error deleting 'sqldatabase-sample-ierjhhobssp44qeu3ueo': error fetching live state: error reading underlying resource: Error reading SQLDatabase "projects/rleidle-cnrm/instances/sqlinstance-sample-ierjhhobssp44qeu3ueo/databases/sqldatabase-sample-ierjhhobssp44qeu3ueo": googleapi: Error 400: Invalid request: Invalid request since instance is not running., invalid
```


Test results with the `transformSQLDatabaseReadError` function:

```
2020/04/21 13:28:35 [DEBUG] Transformed SQLDatabase error
2020/04/21 13:28:35 [WARN] Removing SQL Database Instance "sqlinstance-sample-khh7ccde5fmr2i1ldlkp" because it's gone
--- PASS: TestCRUD (1.07s)
    --- PASS: TestCRUD/basic-sqldatabase (428.69s)
PASS
ok  	cnrm.googlesource.com/cnrm/pkg/gcptokrm/gcpclient	432.557s
```

**Comment by rileykarson** [comment]
Thanks! Superseded with https://github.com/GoogleCloudPlatform/magic-modules/pull/3396.

**Pull request closed without merging**
