### PR TITLE
update formatting

### PR DESCRIPTION
**Pull request by pradeepbhadani**
Adding changes from https://github.com/terraform-providers/terraform-provider-google/pull/5097/files

### CODE REVIEW

**Comment by pradeepbhadani** [comment]
@paddycarver  This is the new PR replacing https://github.com/terraform-providers/terraform-provider-google/pull/5097

**Comment by pradeepbhadani** [comment]
@danawillow

**Comment by danawillow** [comment]
hashicorp gets the full two weeks of christmas / new years off, so paddy won't be back until next week. I'm happy to take care of it this time, but I'd prefer that tagging me into PRs doesn't become a habit :)

**Comment by pradeepbhadani** [comment]
Hi @danawillow , I thought paddy might be busy so tagged you as you are very active on this repo.


@paddycarver suggested removing one commit so I raise this new PR after removing problematic commit. I will wait for @paddycarver to have a look at this PR and comment.

Is there an easy way to identify the files that are managed by the Magic module or hand-written?

**Comment by danawillow** [comment]
Yeah, I'll let him decide if he wants to try upstreaming it once he's back next week.

You can tell if a file is autogenerated by checking if it has a comment at the top that says
```
***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
```

Even if a file is written by hand, you can still modify it in the magic modules repo if you'd like- those live at https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform. We have some documentation around this in the [CONTRIBUTING guide](https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#autogenerated-resources). Hope that helps!

**Comment by danawillow** [comment]
@pradeepbhadani, I'm sorry again about the delay. This currently looks like it has some merge conflict markers as well as some changes that I believe you did already propose against MM. If there's anything else outstanding re: this PR, please feel free to open a new one!

**Pull request closed without merging**
