### PR TITLE
Use the v1 instead of beta API for IPv6.

### LINKED ISSUE #445: Use the v1 instead of beta API for IPv6 support now that the feature is in GA
See announcement:
https://cloudplatform.googleblog.com/2017/09/announcing-ipv6-global-load-balancing-ga.html

Impacted resource:
* compute_global_address
* compute_global_forwarding_rule

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #445 

IPv6 support is now in GA.

I left the codepath handling the `resource_compute_global_address.go` even if there is no beta feature anymore. My thinking is that it will make adding support for future beta feature easier.

### CODE REVIEW

**Comment by rosbo** [comment]
```sh
TF_ACC=1 go test ./google -v -run TestAccComputeGlobalAddress_ -timeout 120m
=== RUN   TestAccComputeGlobalAddress_importBasic
--- PASS: TestAccComputeGlobalAddress_importBasic (23.81s)
=== RUN   TestAccComputeGlobalAddress_basic
--- PASS: TestAccComputeGlobalAddress_basic (23.54s)
=== RUN   TestAccComputeGlobalAddress_ipv6
--- PASS: TestAccComputeGlobalAddress_ipv6 (23.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	71.035s

TF_ACC=1 go test ./google -v -run TestAccComputeGlobalForwardingRule_ -timeout 120m
=== RUN   TestAccComputeGlobalForwardingRule_basic
--- PASS: TestAccComputeGlobalForwardingRule_basic (114.80s)
=== RUN   TestAccComputeGlobalForwardingRule_update
--- PASS: TestAccComputeGlobalForwardingRule_update (127.48s)
=== RUN   TestAccComputeGlobalForwardingRule_ipv6
--- PASS: TestAccComputeGlobalForwardingRule_ipv6 (113.87s)
=== RUN   TestAccComputeGlobalForwardingRule_labels
--- PASS: TestAccComputeGlobalForwardingRule_labels (137.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	493.940s
```

**Comment by rosbo** [comment]
I also hate dead code. To make it easy to bring it back, I will squash my commits in two commits. The first one will contain the changes we have now and the second will contain only the diff removing the beta code. This way, it will be easy to do a git revert in the future if nothing else has changed in this file.

**Comment by rosbo** [comment]
@selmanj I deleted the dead code and reorganized the commits so it is easy to revert only one to get back the beta code paths.

**Comment by selmanj** [comment]
👍 No changes were needed to the tests to not use beta?

**Comment by rosbo** [comment]
You are right, I forgot about the tests. I updated the tests so they don't use anything beta. I reran them again and they all passes:
```
TF_ACC=1 go test ./google -v -run TestAccComputeGlobalAddress_ -timeout 120m
=== RUN   TestAccComputeGlobalAddress_importBasic
--- PASS: TestAccComputeGlobalAddress_importBasic (24.01s)
=== RUN   TestAccComputeGlobalAddress_basic
--- PASS: TestAccComputeGlobalAddress_basic (23.24s)
=== RUN   TestAccComputeGlobalAddress_ipv6
--- PASS: TestAccComputeGlobalAddress_ipv6 (24.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google/google	71.520s
```

**Pull request merged**
