### PR TITLE
Suppress perpetual diff on logging sink filter with surrounding whitespaces

### PR DESCRIPTION
**Pull request by tmshn**
This pull request fixes annoying perpetual diff on `google_logging_project_sink` with `filter` attribute defined using heredoc.

```hcl
resource "google_logging_project_sink" "gke_error" {
	name = "gke_error"
	project = "..."
	destination = "..."
	filter = <<-EOS
		(resource.type=\"gke_cluster\" OR resource.type=\"container\")
		AND severity>=ERROR
		EOS
}
```

Previously, this gives following plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

~ google_logging_project_sink.foo
     filter:            "(resource.type=\"gke_cluster\" OR resource.type=\"container\")\nAND severity>=ERROR" => "(resource.type=\"gke_cluster\" OR resource.type=\"container\")\nAND severity>=ERROR\n"

Plan: 0 to add, 1 to change, 0 to destroy.
```

(See trailing `"\n"`)

It'll be fixed into:
```
No changes. Infrastructure is up-to-date.
```

### CODE REVIEW

**Comment by tmshn** [comment]
I did 👍 62e4877

**Comment by tmshn** [comment]
@ndmckinley ping

**Comment by danawillow** [comment]
(just passing by, linking to #1162 which this fixes)

**Comment by ndmckinley** [comment]
Looks great!  I'm just going to run those tests one more time, then merge.

**Comment by ndmckinley** [comment]
Oh, man, my mistake...

```
        * google_logging_organization_sink.heredoc (import id: organizations/*******/sinks/tf-test-sink-1797k6zi8w): import google_logging_organization_sink.heredoc (id: organizations/*******/sinks/tf-test-sink-1797k6zi8w): resource google_logging_organization_sink doesn't support import
```

I apologize for that.  Your call - obviously it'd be better to make those resources importable, but that falls outside the range of what I think it's okay to ask for as a condition of accepting your PR.  Feel free to just undo that last commit.  I'll get back to you next business day.

**Comment by tmshn** [comment]
@ndmckinley I partially reverted the last commit (only project sink looks importable, so it remains).

**Comment by ndmckinley** [comment]
Test passes, merging.

**Pull request merged**
