### PR TITLE
Adding functionality for static internal addresses to be configured

### LINKED ISSUE #366: reserve static internal ip address
I would like the ability to reserve a static internal ip address as described here 
https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address

### PR DESCRIPTION
**Pull request by elliottsam**
This adds the ability to reserve internal addresses and resolves #366

### CODE REVIEW

**Comment by paddycarver** [comment]
This looks like a duplicate of #488.

**Comment by elliottsam** [comment]
Oh my mistake would it be possible to add specifying the IP address to that one? As it seems to not allow that at the moment

**Comment by paddycarver** [comment]
Ah, you're correct. I'd prefer to add that functionality to #488 (which I believe should only take a couple of modifications to the code--I'll do that) rather than go forward with this one, just because #488 properly supports the beta API rather than forcing all users of the `compute_address` resource to use the beta API even if they don't need to. How do you feel about this path forward?

**Comment by elliottsam** [comment]
Yeah that seems like a good way to go with it. Thanks

**Pull request closed without merging**
