### PR TITLE
Move Bigtable config to cluster block.

### PR DESCRIPTION
**Pull request by paddycarver**
Match the bigtable_instance resource to the API structure, deprecating
the inlined config parameters. This is a complicated deprecation,
because we don't want to ForceNew when updating to use the new
undeprecated fields, but we want to ForceNew if they change.

This is achieved using a CustomizeDiff.

### CODE REVIEW

**Comment by paddycarver** [comment]
> Can you add a test with multiple clusters?
>
> Does using a default zone make sense in the multiple-cluster world? Can we make a Cloud Bigtable with 2 clusters in the same zone? I don't think that makes sense and they should be in multiple zones, so the API probably won't allow it.

I have no idea. Since this wasn't _supposed_ to be enhancement work, just deprecation, how would you feel about me just setting `MaxItems` to 1 for now, and we can sort through the enhancements at a later date? At this point, I just want to get the config in the right shape, I don't really care about supporting multiple clusters _today_. We could do that work some other time.

**Comment by paddycarver** [comment]
I'd be down for removing `getZone` in 2.0.0, but we can't do that _today_.

**Comment by rileykarson** [comment]
Oh yup! That's what I meant by that*

**Comment by paddycarver** [comment]
Cool, I already have #1672 in the 2.0.0 milestone, so we've got an issue to track that enhancement.

**Pull request merged**
