### PR TITLE
correct import statement for cloud functions

### PR DESCRIPTION
**Pull request by JaymoKang**

### CODE REVIEW

**Comment by c2thorn** [comment]
Hi @JaymoKang, looks like both methods are possible here:
{projectId}/{regionId}/{cloudFunctionName}
or
{cloudFunctionName}

The original documentation is referring to the cloud function name of the example above

**Comment by JaymoKang** [comment]
I recently got this error while performing import. My provider listed the project in which the cloudfunction was being drawn from
```
# terraform import module.module-name.google_cloudfunctions_function.function function-name
module.module-name.google_cloudfunctions_function.function: Importing from ID "function-name"...
module.module-name.google_cloudfunctions_function.function: Import prepared!
  Prepared google_cloudfunctions_function for import
module.module-name.google_cloudfunctions_function.function: Refreshing state... [id=function-name]

Error: Invalid CloudFunction id format, expecting `{projectId}/{regionId}/{cloudFunctionName}`
```

**Comment by c2thorn** [comment]
@JaymoKang which version of the Google Provider are you using?

**Comment by JaymoKang** [comment]
2.20

**Comment by c2thorn** [comment]
Gotcha. Support for the {cloudFunctionName} import method was added in 3.X series, and the documentation was changed to reflect that. I recommend upgrading your version of the provider to the latest supported version.

Closing this as the documentation shows as intended.

**Pull request closed without merging**
