### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by jsoref** [comment]
I'm happy to split this out, but I need hints about how to do it. The section you linked to doesn't make it readily apparent what I should do.

If you give me a sequence of repos to check/fix, I can apply things in that sequence first and circle here last (or in order).

**Comment by danawillow** [comment]
The repo is https://github.com/GoogleCloudPlatform/magic-modules. Once changes are made there, they get propagated out to a bunch of different repos, so that's the only one that would need to be done.

**Comment by jsoref** [comment]
Ok, finally got it working...

For my reference:
```sh
#!/bin/sh
DIFF="-r master -r spelling"
if [ "$MODE" = "rs" ]; then
    PREFIX='rs "'
    INFIX='" "'
    SUFFIX='"\n'
elif [ "$MODE" = "go" ]; then
    PREFIX='g "'
    INFIX='"\necho "-> '
    SUFFIX='"\n'
else
    PREFIX='s/'
    INFIX='/'
    SUFFIX='/g;\n'
fi

if [ ! -z "$1" ]; then
    DIFF="$1"
fi

(d --color always $DIFF -U0|\
    perl -ne 'next unless /^\x1b\[0;3[12]m/;s/.*?(\x1b\[0;3[12];1;4m)/$1/g;print'|\
    perl -pne 's/\x1b\[0m.*//' |\
    perl -pne 's!\x1b\[0;31;1;4m(.*)\n!'"$PREFIX"'$1!;s!\x1b\[0;32;1;4m(.*)\n!'"$INFIX"'$1'"$SUFFIX"'!;'
)|sort -u;
```

```sh
for a in $(hg log -T '{rev} ' -r .%master); do
  X="$(MODE=rs .hg/patches/patch-to-perl -c$a)";
  (
    cd ../magic-modules/;
    echo "$X";
    sh -c "$X"
  ) 2>&1; done |
perl -ne 'next if /^Required ruby|^To install do/;print'
```

**Comment by jsoref** [comment]
This is superseded by #4259

**Pull request closed without merging**
