### PR TITLE
 update formatting to display in code block 

### PR DESCRIPTION
**Pull request by pradeepbhadani**
Currently it does not display `identity_namespace` block as code block but display as below here https://www.terraform.io/docs/providers/google/r/container_cluster.html#identity_namespace

`hcl workload_identity_config { identity_namespace = "${data.google_project.project.project_id}.svc.id.goog" }`

### CODE REVIEW

**Comment by pradeepbhadani** [comment]
@paddycarver  Can you take a look into this?

**Comment by pradeepbhadani** [comment]
@danawillow

**Comment by paddycarver** [comment]
This needs to be upstreamed, but for some reason my upstreaming isn't working. I'll get it working again in ~6 hours when more people are in the office, and get this upstreamed and merged. Sorry for the delay.

**Comment by pradeepbhadani** [comment]
Thanks @paddycarver

**Comment by pradeepbhadani** [comment]
@paddycarver  Can you please merge this PR?

**Comment by pradeepbhadani** [comment]
@danawillow

**Comment by paddycarver** [comment]
Hey @pradeepbhadani. Because we're upstreaming this to https://github.com/GoogleCloudPlatform/magic-modules, the merge commit cef8041fca7df570aea7da332a397d3906c9798c makes merging this a pain. Any chance I could get you to rebase on master?

```
git pull origin master
git checkout fork master
git rebase -i origin/master
```

and drop the merge commit? I can also do this tomorrow, but it'll preserve less of the authorship information than if you do it. Let me know if you want to tackle this, and if I don't hear from you tomorrow, I'll go ahead and do it myself.

**Comment by pradeepbhadani** [comment]
@paddycarver  - For somereason above steps did not worked for me.
I have created a new PR which has these changes without commit `cef8041`.

New PR: https://github.com/terraform-providers/terraform-provider-google/pull/5207

**Pull request closed without merging**
