### PR TITLE
Fix potential perma-diff with metric_descriptor.labels in logging_metric

### PR DESCRIPTION
**Pull request by xanonid**
Fixes: #4141

### CODE REVIEW

**Comment by xanonid** [comment]
It would be helpful, if anyone can shortly explain, why this change is needed at all. I would have expected that it have worked out-of-the-box (`Set: schema.HashResource(...)` auto-set) - but apparently it did not. Are there other places, where this needs to be explicitly set?

**Comment by emilymye** [comment]
Hi @xanonid  - do you have an example of config that recreates this issue? I'm having trouble reproducing, and the default HashSchema calls out to HashResource(schema.Elem), so this shouldn't be necessary?

**Comment by xanonid** [comment]
Hi @emilymye, I will prepare a minimal example, it should be reproducible by having more than one label and then simply reordering the labels after applying. The related bug #4141 has currently 11 thumps-up, so there seems to be really an issue.
I have it also in a slightly complicated setup where adjusting the order of the labels is not a solution as the metric resource is in a more than once used module (and depending on the instance, unfortunately different label orders would be currently needed to be free of perma-diffs).
I do also not understand yet why the fix worked as it should be already the default. Maybe somewhere a proper initialization of the Set is missing...

**Comment by xanonid** [comment]
@emilymye 
I close this PR as the issue seems to be really already fixed - sorry. I had unfortunately a version constraints to an outdated 2.x provider version which had still the issue.

**Pull request closed without merging**
