### PR TITLE
Sort IAM policy bindings by their role name to get simpler diffs

### PR DESCRIPTION
**Pull request by pdecat**
This should resolve https://github.com/terraform-providers/terraform-provider-google/issues/3728

### CODE REVIEW

**Comment by pdecat** [comment]
Can go a step further and sort members of each binding too.

**Comment by pdecat** [comment]
An alternative option may be to convert all `bindings` and `members` attributes from lists to sets but that's way more intrusive.

**Comment by danawillow** [comment]
Will this show diffs for users that already have iam policies defined in their terraform configs?

**Comment by pdecat** [comment]
No it does not.

**Comment by pdecat** [comment]
The diffs are already suppressed by the `jsonPolicyDiffSuppress()` function: https://github.com/terraform-providers/terraform-provider-google/blob/e9aebb8b158646bd1d9b4fbe9854734cd8c09b52/google/resource_google_project_iam_policy.go#L190

**Comment by pdecat** [comment]
Let me provide some examples to demonstrate the result of this change.

**Comment by pdecat** [comment]
Here's a test case configuration: https://gist.github.com/pdecat/4450fbbee34074d9df9cdb56ceac6772

After having applied that configuration with v2.9.1 and commenting [line 86](https://gist.github.com/pdecat/4450fbbee34074d9df9cdb56ceac6772#file-main-tf-L86), here's the plan: https://gist.github.com/pdecat/fd84253c753fa9c20b8995e699da07b4

With this modification, here's the plan: https://gist.github.com/pdecat/629a8d7e733122737002e02bf2f92964

**Pull request merged**
