### PR TITLE
(OLD) Google Cloud Dataproc support

### PR DESCRIPTION
**Pull request by nickithewatt**
Addresses https://github.com/terraform-providers/terraform-provider-google/issues/31 and provides support for Google Cloud Dataproc. @danawillow @radeksimko 

At this stage I have added support for the resources below which all work and have acceptance tests as well - Not sure where / when you run the acceptance tests as they are not run as part of the travis build? There is one acceptance test I added (`TestAccDataprocCluster_withServiceAcc`) which needs a new environment variable to be set in order to work. At present if it doesn't detect the variable it skips the test.   

The jobs are pretty much fleshed out for those wanting to run PySpark and Spark jobs on clusters. I thought I should first get some validation / feedback to see if you are happy with the approach I have taken. Then if necessary I can make any changes before completing the rest. 
**UPDATE** - I have implemented them all now... 

_**resources**_
  - [x] `google_dataproc_cluster`
  - [x] `google_dataproc_job`
    - [x] via `pyspark_config` support for PySpark jobs
    - [x] via `spark_config` support for Spark jobs
    - [x] via `sparksql_config` support for Spark-SQL jobs
    - [x] via `hadoop_config` support for Hadoop jobs
    - [x] via `hive_config` support for Hive jobs
    - [x] via `pig_config` support for Pig jobs

Specifically for `google_dataproc_job`, _create_ essentially _submits_ a job to the cluster to let it run. It does not wait for it to finish. Updating of jobs doesn't really make much sense, and for _delete_ I am genuinely deleting the job. Under normal circumstances, Dataproc won't let you delete active jobs. I have therefore added a `force_destroy` option which if true, will first cancel the job before deleting.

In any case, looking forward to your comments.
Thanks
Nicki

### CODE REVIEW

**Comment by nickithewatt** [comment]
OK, I have finished all the other job types as well, so this is pretty much feature complete. CC @danawillow @radeksimko @grubernaut

**Comment by grubernaut** [comment]
Hi @nickithewatt, thank you for the amazing contribution! Welcome! 

While both @radeksimko and I could review this PR, I believe this is better suited for the community maintainers of the Google Provider, as they are likely the most familiar with the provider's current state. Please feel free to reach out to us for any help or issues that may arise, however. 
Thanks again!

**Comment by danawillow** [comment]
Hey @nickithewatt, to answer your question about acceptance tests- we run them nightly on all checked-in code, but we don't run them automatically on PR review. I did go ahead and run them myself and they all passed (I skipped the service account one, will run it again once I've looked through what it entails).

I should be able to get to your review within the next few days, but it's a bit long- if you're ok with it, I'd love to see each resource in a separate PR that way we can check them in incrementally instead of needing to wait for a review of both. If that's going to be significant effort though let me know and I'll review the whole thing.

**Comment by nickithewatt** [comment]
Hi @danawillow, thanks for looking to review this, apologies it is a bit big!

I can probably try and split this into two different PR's, one for `google_dataproc_cluster` and a separate one for `google_dataproc_job`. It will require a bit of rejigging and probably some squashing but its definitely doable! 

The only thing is that there will be a dependency on the ordering they are processing, with  `google_dataproc_cluster` being a dependency for `google_dataproc_job` but otherwise that should be fine.

If you are happy, I will create two new separate PR's one for each, and then reference them here and we can go from there?

**Comment by danawillow** [comment]
That would be great, thanks!

**Comment by nickithewatt** [comment]
@danawillow Done, PRs https://github.com/terraform-providers/terraform-provider-google/pull/252 and https://github.com/terraform-providers/terraform-provider-google/pull/253. 
Unfortunately at this stage, the 2nd PR https://github.com/terraform-providers/terraform-provider-google/pull/253 includes the commits from the cluster PR as well. Once the cluster PR hopefully makes its way to master, the diff should be more apparent :)

Many thanks
Nicki

**Comment by danawillow** [comment]
Closing in favor of #252 and #253.

**Pull request closed without merging**
