### PR TITLE
Allow for legacy domain-scoped project IDs.

### PR DESCRIPTION
**Pull request by ubschmidt2**

### CODE REVIEW

**Comment by ubschmidt2** [comment]
Thanks, going to add a unit test for the regular expression.

**Comment by ubschmidt2** [comment]
Even better, going to change this to use https://github.com/terraform-providers/terraform-provider-google/blob/da5c5e8b7c8565a5aec2d088694127f77c468ec6/google/validation.go#L14.

**Comment by ndmckinley** [comment]
Great - when that's done, I'll go ahead and merge it.  :+1:

**Comment by ubschmidt2** [comment]
PTAL.

**Pull request merged**
