### PR TITLE
SQL DB Instance has attribute first_ip_address

### PR DESCRIPTION
**Pull request by genevieve**
Related Issues:

https://github.com/terraform-providers/terraform-provider-google/issues/912
https://github.com/hashicorp/terraform/issues/17048

### CODE REVIEW

**Comment by danawillow** [comment]
I see in the other issue that a workaround of using `TF_WARN_OUTPUT_ERRORS=1` until the new syntax comes out was suggested- did that work?

**Comment by genevieve** [comment]
Since the terraform doesn't apply without that environment variable, it means resources that all our teams use in CI/CD pipelines would have to support that, as well as asking it of all ours that go directly to use these terraform templates. It wasn't really something we wanted to recommend since it risks actually swallowing relevant errors. 

When we choose one output syntax or the other either the database-turned-off case works and the database-turned-on fails during `terraform apply`, or choosing a different syntax causes the opposite.

**Comment by danawillow** [comment]
Thanks @genevieve! That sounds reasonable, and the code looks good. Merging now.

**Comment by danawillow** [comment]
Oh wait, I got ahead of myself. I'm going to keep it in, but would you mind sending a follow-up PR for changes to the docs to add this attribute? Please tag me in it and I'll review it right away.

**Pull request merged**
