### PR TITLE
update compute_attached_disk.html.markdown

### PR DESCRIPTION
**Pull request by pradeepbhadani**
update resource name from `compute_attached_disk` to `google_compute_attached_disk`

### CODE REVIEW

**Comment by pradeepbhadani** [comment]
@tysen  @megan07  Can you pleae review this PR?

**Comment by pradeepbhadani** [comment]
@slevenick Can you review this PR?

**Comment by pradeepbhadani** [comment]
@danawillow

**Comment by pradeepbhadani** [comment]
Thanks @megan07 
@tysen  Can you please review the change also?

**Comment by danawillow** [comment]
Only one reviewer is necessary, hashibot just got excited. Removing Ty.

**Pull request merged**
