### PR TITLE
Add docs for first_ip_address on sql db instance.

### PR DESCRIPTION
**Pull request by genevieve**
@danawillow I saw you already updated the changelog, so I only updated the doc for the sql db instance. Let me know if I missed anything or if you prefer a different wording!

Thank you!!! 

Gen

### CODE REVIEW

**Comment by danawillow** [comment]
Would you mind adding a one-sentence description of what the use case for this is? (just in case someone wonders in the future why this particular list has its first element broken out) You can link to the issues if you want.

**Comment by genevieve** [comment]
Does that sound better?

**Comment by genevieve** [comment]
I can also add the issue from the terraform core repo

**Comment by danawillow** [comment]
That's perfect, thanks!

**Pull request merged**
