### PR TITLE
Google Cloud Storage Transfer resource

### PR DESCRIPTION
**Pull request by akramhussein**
This is a full implementation of the [Google Cloud Storage Transfer](https://cloud.google.com/storage-transfer/docs/) resource that addresses #1286 issue.

Full documentation for Terraform docs is also included that is primary sourced from official Google Docs.

This supersedes a previous PR #2164 that was incomplete.

I've not had a chance to write unit tests but believe it would be good to get your feedback at this stage on anything that I should change/improve. I have tested it significantly manually.

### CODE REVIEW

**Comment by akramhussein** [comment]
I believe this PR could be improved with:

1. Unit tests
2. Adding a `data_source` to get the `Storage Transfer Service Account` which shouldn't be too hard.

**Comment by akramhussein** [comment]
* Added datasource to get the project's service account
* Added datasource test
* Added resource basic test

**Comment by rileykarson** [comment]
Hey @akramhussein! This is awesome - I'm really sorry this fell through the cracks for so long.

In the meantime since you wrote this code, we've made a transition from direct contributions in this repository to a code generation repository, [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules). We're doing that to allow us to generate two nearly identical providers, `google` and [`google-beta`](https://github.com/terraform-providers/terraform-provider-google-beta).

Looking over this code briefly, I'd love to be able to click approve and merge this right now, but even excluding vendor changes we're looking at +- ~1300-1500 lines of diff. There's no way I'd be able to feel confident having reviewed it; so ideally, we'd split out these changes into a few different PRs.

I see a few ways to go forward here;

* You split out the changes into a few separate PRs, and make them against Magic Modules
	* This looks pretty simple! These files are almost all new, so it's almost just a matter of copy-pasting and making the right commits. They would be:
		* Vendoring the new library
		* Adding the service account datasource
		* Adding the storage transfer job
* One of the provider maintainers takes over the PR and gets it merged into MM
	* We've taken our time here, and we have no expectation that you still have the bandwidth/context to work on this. We'll gladly take over the changes & bring them past review and in to the repo.
* Either you or a provider maintainer reuse the existing handwritten service account datasource code, and autogenerate the Transfer Job resource using Magic Modules.
	* This PR would be _much_ easier to review, and means that the resource automatically gets MM features like import (if supported) and timeouts, as well as bug fixes that we are able to roll out with MM.
	* Unfortunately it means it clobbers the work you've already done on the resource.
	* https://github.com/GoogleCloudPlatform/magic-modules/pull/696 is a good reference for the work it takes to add a new product + a single resource

Please let me know your preference here, and thanks again for the contribution!

**Comment by akramhussein** [comment]
Hi @rileykarson - will have a think over the weekend and get back to you ASAP.

**Comment by akramhussein** [comment]
Hi @rileykarson just wanted to clarify with option 1, what do you mean by `make them against Magic Modules`? I'm happy to split the commits up and get that done relatively soon but not sure what the MM part involves.

**Comment by rileykarson** [comment]
Ah! My apologies - I didn't explain what I meant there.

As stated above, we're using [Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules) as the source of truth for both this provider ([`google`](https://github.com/terraform-providers/terraform-provider-google)) and the beta provider ([`google-beta`](https://github.com/terraform-providers/terraform-provider-google-beta)). To sync changes between both providers, PRs are written against the MM repo.

We're migrated a few PRs made against this repo, but since this would already involve moving around files / git commits, it's probably easier to PR against that repo to begin with.

Here's a [community PR made against this repo](https://github.com/terraform-providers/terraform-provider-google/pull/2287) and the [corresponding MM changes](https://github.com/GoogleCloudPlatform/magic-modules/pull/904). It's generally just moving files from `google/` to the appropriate subdirectory of `third_party/terraform` in MM. Vendor changes will need to be made here and against [`google-beta`](https://github.com/terraform-providers/terraform-provider-google-beta), they aren't managed by MM.

**Comment by akramhussein** [comment]
Cool - makes sense. I will do that.

**Comment by akramhussein** [comment]
Quick update - still planning to do this! Just a bit busy at the moment. Thanks!

**Comment by rileykarson** [comment]
Thanks for the update! Feel free to take your time, & if you suddenly have no more time to do this just let us know and we'll gladly shepherd the changes through.

**Comment by akramhussein** [comment]
Hi @rileykarson - I'm making all these changes now. 
Please ignore this PR as it's gone a bit haywire - everything is being done in new PRs. 

I've so far created:

* [Adding the service account datasource to MM's third_party dir](https://github.com/GoogleCloudPlatform/magic-modules/pull/1068)
* [Adding the storage transfer job to MM's third_party dir](https://github.com/GoogleCloudPlatform/magic-modules/pull/1069)
* https://github.com/terraform-providers/terraform-provider-google-beta/pull/245
* https://github.com/terraform-providers/terraform-provider-google/pull/2690

I believe I still need to add:

* PR for Adding the `storage transfer job resource` to this repo and `beta` with also the line in the `provider.go` to hook it up?
* PR for Adding the `storage transfer service account datasource` to this repo and `beta` with also the line in the `provider.go` to hook it up?

So 4 more PRs. Is that correct?

**Comment by rileykarson** [comment]
Nope - you've submitted all the PRs you need. Magic Modules will create PRs against both repos, and files like `provider.go` can be modified inside MM: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/utils/provider.go.erb

Normally MM would auto-generate "downstream" PRs to this repo and the beta repo, but since you're a first time contributor each build needs to be triggered manually. I'll kick off a build once we've merged the vendoring changes. I believe once a PR has been submitted it will generate automatically, but I'm not 100% on that.

**Comment by akramhussein** [comment]
@rileykarson can this be closed now?

**Comment by akramhussein** [comment]
Also #1286

**Comment by rileykarson** [comment]
Yep, thanks! Superseded by https://github.com/GoogleCloudPlatform/magic-modules/pull/1069

**Pull request closed without merging**
