### PR TITLE
added block in README.md on upgrading

### PR DESCRIPTION
**Pull request by nodesocket**

### CODE REVIEW

**Comment by paddycarver** [comment]
Hey @nodesocket, thanks for the feedback! I'm realising we don't really have `upgrade` covered in our docs anywhere.

I'm hesitant to add it to just the `terraform-provider-google` README, though, because it really applies to all our providers. If it's added to https://www.terraform.io/docs/configuration/providers.html instead, does that solve your concern? Do you think we need to add a pointer to that page to the README?

**Comment by nodesocket** [comment]
@paddycarver sure that makes sense updating the official docs, but I don't think it hurts to add to the `README.md` as well. Your call though.

**Comment by rosbo** [comment]
I agree with @nodesocket, it doesn't hurt to put it there. I like having the most important commands surfaced in our project's readme.

**Comment by paddycarver** [comment]
Agreed, updating this to point to the docs on the website has been on my TODO list for far too long. Apologies for the delay here.

**Comment by paddycarver** [comment]
Does #701 achieve what you were looking for, @nodesocket?

**Pull request merged**
