### PR TITLE
Renaming datasources files and links inside erb.

### PR DESCRIPTION
**Pull request by jayolmos**
Hello :)

this PR is related the documentation structure issue  in #2876 .

I was reviewing the document structure in aws and azure and for standard I think Riley is right to go for no prefix inside datasources structure. So this PR moves the files and change the links inside the google.erb file.

Inside the google.erb in master and also this PR, there's two missing links:

- compute_resource_policy
- secret_manager_secret_version

I don't know if this is ok with the contributing guide so please let me know if I can help in anything related to this issue.

Thanks!

### CODE REVIEW

**Comment by slevenick** [comment]
Hey @jayolmos this PR is marked as draft, is that intentional, or is it ready for review?

**Comment by jayolmos** [comment]
Hello @slevenick as the issue was not fully defined I wasn't sure if open as draft or as ready for review. So if it looks good I can move it to review and take a look to the failed links.

**Comment by slevenick** [comment]
Yeah, I think it would be good to do this. One thing to note is that some work around generating the `google.erb` file was done recently, so you may notice merge issues now. See: https://github.com/terraform-providers/terraform-provider-google/issues/6001

Also, if you are able it would be preferable to make this PR against https://github.com/GoogleCloudPlatform/magic-modules which is the tool that generates these files. Normally I could upstream a PR against this repo to that one, but given that most of the changes are renames to files it could get tricky.

**Comment by jayolmos** [comment]
Thanks! Closing this PR and working in the new one.

**Pull request closed without merging**
