### PR TITLE
Better DiffSuppressFunc for disk image field

### LINKED ISSUE #861: Resize disk destroy and recreate vm
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_disk
- google_compute_instance

### Terraform Configuration Files
resource "google_compute_disk" "disk" {
    name    = "disk"
    type    = "pd-standard"
    zone    = "europe-west1-b"
    size    = "50"
    image = "debian-cloud/debian-8"
}

resource "google_compute_instance" "vm" {
  name         = "vm"
  machine_type = "n1-standard-1"
   zone    = "europe-west1-b"

  boot_disk {
     source ="${google_compute_disk.disk.self_link}"
  }

  network_interface {
     subnetwork = "default"

  }

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
    min_cpu_platform="Intel Skylake"

}

### Expected Behavior
From what I saw there : https://github.com/hashicorp/terraform/pull/15077, GCP provider support resize of disk without delete/recreate the instance.

### Actual Behavior
When i re-run the script with size = "70". The VM is deleted and recreated.
GCP is able to resize the disk on the fly even boot disk so I expect to have the size increased but without deleting re-creating the VM.

### Steps to Reproduce
1. terraform apply on the script above
2. change size of the disk to 70
3. terraform apply

### References
https://github.com/hashicorp/terraform/pull/15077

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #861 

Resizing disk while the instance is running is already supported. The problem came from a diff in the image field causing a ForceNew.

```sh
image:                      "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8-jessie-v20171213" => "debian-cloud/debian-8" (forces new resource)
```

This PR adds a better DiffSuppressFunc for the disk image field which allows to resize the disk without causing a force new.

### CODE REVIEW

**Comment by rosbo** [comment]
```sh
--- PASS: TestAccComputeDisk_timeout (0.09s)
--- PASS: TestAccComputeDisk_encryption (23.44s)
--- PASS: TestAccComputeDisk_basic (24.17s)
--- PASS: TestAccComputeDisk_update (45.20s)
--- PASS: TestAccComputeDisk_deleteDetach (62.05s)
--- PASS: TestAccComputeDisk_fromSnapshot (107.61s)
```

**Comment by rosbo** [comment]
I wasn't aware of the family case. I will update this PR to handle it.

**Comment by rosbo** [comment]
@danawillow I handle more cases now. Could you re-review it? Thanks

**Comment by chandan-rapido** [comment]
when I try to resize disk it is still replacing the instance. My Terraform version is v0.12.9.

terraform plan output:

          ~ initialize_params {
              ~ image  = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20190816" -> "ubuntu-1604-xenial-v20190816"
              ~ labels = {} -> (known after apply)
              **~ size   = 200 -> 250 # forces replacement**
                type   = "pd-ssd"
            }
        }

**Pull request merged**
